"""Phase 4C post-session reading constants."""

from __future__ import annotations

BARNUM_TECHNIQUES = (
    "DOUBLE_HEADED_STATEMENT",
    "UNIVERSAL_VULNERABILITY",
    "SUBJECTIVE_COMPLETION",
    "FLATTERY_OF_DISCERNMENT",
    "MODAL_FALLACY",
)

COMPOSITION_STRATEGIES = (
    "REFRACTION",
    "MIRRORING",
    "ACCUMULATION",
    "THRESHOLD",
    "RETURNING motif",
    "CONTRAST",
    "GENTLE HYPOTHESIS",
)

ARCHETYPES = (
    "Archivist",
    "Lantern-Bearer",
    "Anchor",
    "Harbinger",
    "Seeker",
    "Keeper",
    "Riddle-Holder",
    "Warden",
    "Mapmaker",
    "Pilgrim",
    "Stillness",
    "Witness",
    "Tide-Reader",
    "Gardener",
    "Wanderer",
    "Pathfinder",
    "Ember-Holder",
    "Echo",
    "Mender",
    "Seamstress",
    "Night-Watcher",
    "Traveler",
    "Conductor",
    "Quiet Oracle",
    "Horizon-Keeper",
    "Mirror-Bearer",
    "Root-Listener",
)

TITLE_FRAGMENTS = (
    "The Quiet Before the Question",
    "The Lantern in the Hallway",
    "The Thread That Returns",
    "The Weather of Unspoken Things",
    "The Keeper of Deferred Answers",
    "The Blue Hour of Reconsideration",
    "The Bell in the Empty Room",
    "The Worn Path of Second Thoughts",
    "The Soft Echo of a Missing Sentence",
    "The Map Beneath the Surface",
    "The Mirror of Delayed Recognition",
    "The Lantern Between Two Silences",
    "The Orchard of Quiet Confidence",
    "The River That Returns the Same Question",
    "The Shape of a Careful Pause",
    "The Hearth of Less Certain Certainty",
    "The Door with the Listening Knob",
    "The Candle Behind the Curtain",
    "The Grammar of the Unsaid",
    "The Strong Light of Gentle Resolve",
    "The Hush Around a Difficult Truth",
    "The Small Door of Reframing",
    "The Rain That Changes the Path",
    "The Thread of a Wiser Delay",
    "The Hidden Comfort in Repetition",
    "The Tender Weight of an Unfinished Thought",
    "The Familiar Sound of a New Beginning",
)

READING_FRAGMENTS = (
    "A patient rhythm keeps returning to the same door, asking for a gentler opening.",
    "Silence is carrying more than it first appears to carry.",
    "The work is not in the first answer but in the second thinking of it.",
    "A difficult truth becomes softer when it is held with patience.",
    "An unfinished thought may be doing most of the work at the edges.",
    "The next chapter begins where repetition stops pretending to be certainty.",
    "A careful pause can become a kind of intelligence.",
    "The honest path is often the one that asks for less certainty.",
    "Meaning is gathering itself in the small spaces between declarations.",
    "What feels unresolved may simply be waiting for a more spacious language.",
    "There is wisdom in noticing what returns without being forced.",
    "The old question has changed its face, and that is a form of growth.",
    "A steady eye on the light can reveal what urgency hides.",
    "The story is not breaking; it is becoming more precise.",
    "A modest openness can carry a larger truth than a dramatic answer.",
    "The answer is already present in the way the pause is held.",
    "The next step is not louder; it is more honest.",
    "A pattern that once felt repetitive is beginning to look like guidance.",
    "The calmest insight often arrives after the feeling has stopped arguing.",
    "A soft reconsideration may be the clearest signal of all.",
    "What was ignored in the moment may become invaluable in reflection.",
    "Attention is gathering around a deeper thread than the first impression suggested.",
    "The path broadens when the mind stops trying to conquer uncertainty.",
    "There is a gentle authority in the rhythm of returning.",
    "A curious refusal to rush may eventually reveal the truest direction.",
    "Resolution is not the same as certainty; one can be brave without being decisive.",
    "The smallest honest adjustment can redirect a large emotional arc.",
)

FORBIDDEN_SPOILERS = (
    "you said",
    "system matched",
    "system detected",
    "navarasa",
    "ocr detected",
    "sentiment score",
    "evidence_id",
    "inference_id",
    "event_id",
    "telemetry",
    "shanta",
    "raudra",
    "hasya",
    "karuna",
    "bibhatsa",
    "adbhuta",
    "bhayanaka",
    "veera",
    "confidence",
    "gemini",
    "parrot turn",
)

CARD_COUNT = 27
